
language: objective-c  #1
osx_image: xcode9.3 #2

install:
  - gem install xcpretty

jobs:
  include:
- script: xcodebuild clean build test -project TDDDemo.xcodeproj -scheme TDDDemo -destination "platform=iOS Simulator,name=iPhone 6, OS=11.3" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO | xcpretty -c


